name: Simplified Release Management

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (leave empty for auto-increment)'
        required: false
        type: string
  push:
    branches:
      - release-branch

jobs:
  update-and-propagate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=${CURRENT_VERSION}" >> $GITHUB_OUTPUT

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event.inputs.version_override }}" != "" ]; then
            echo "new_version=${{ github.event.inputs.version_override }}" >> $GITHUB_OUTPUT
          else
            IFS='.' read -r major minor build <<< "${{ steps.current_version.outputs.current_version }}"
            new_build=$((build + 1))
            NEW_VERSION="${major}.${minor}.${new_build}"
            echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Update package.json
        run: |
          npm version ${{ steps.version.outputs.new_version }} --no-git-tag-version
          # Prevent package-lock.json from being modified
          git checkout package-lock.json

      - name: Inject version into HTML
        run: |
          VERSION=${{ steps.version.outputs.new_version }}
          sed -i "s/<meta name=\"version\" content=\".*\" \/>/<meta name=\"version\" content=\"${VERSION}\" \/>/" ./src/index.html

      - name: Commit changes to release branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add package.json ./src/index.html
          git commit -m "Update version to ${{ steps.version.outputs.new_version }}"
          git push origin release-branch

      - name: Create Pull Request to Main
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-branch
          base: main
          title: 'Propagate updates to main'
          body: |
            Updates:
            - Updated version in package.json to ${{ steps.version.outputs.new_version }}
            - Updated version in ./src/index.html
          commit-message: 'Propagate version updates to main'
          delete-branch: false

      - name: Enable Auto-Merge for PR
        if: steps.create-pr.outputs.pull-request-number
        run: |
          pr_number="${{ steps.create-pr.outputs.pull-request-number }}"
          gh pr review "$pr_number" --approve
          gh pr merge "$pr_number" --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
